name: Release version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set new version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN_S }}
          tag_prefix: 
          default_bump: false
          custom_release_rules: patch:patch,minor:minor,major:major
      - name: Set new GitHub Release version
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN_S }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}